/**
 * Demo markers — clearly separates DEMO/MOCK from REAL/PRODUCTION.
 *
 * Every screen or component that uses demo data should reference this,
 * making it easy to audit what is mocked and what needs a real implementation.
 */

export const IS_DEMO_MODE = true

export const DEMO_MARKERS = {
  auth: "DEMO: No real authentication. User is hard-coded.",
  database: "DEMO: No real database. Data is in-memory mock.",
  ai: "DEMO: AI responses are scripted, not generated by an AI provider.",
  labs: "DEMO: No actual OCR or file processing. Sample lab data only.",
  safetyEngine: "DEMO: Safety rules are simple heuristics, NOT medically validated.",
  wearable: "DEMO: No wearable integration. Vitals are sample data.",
  clinicalRules: "DEMO: No clinical rules loaded. Architecture only.",
  notifications: "DEMO: No real push notifications.",
  storage: "DEMO: No secure file storage.",
} as const

export type DemoMarkerKey = keyof typeof DEMO_MARKERS
